#!/bin/bash
#
# Init script to manage ActiveMQ runtime
#
# Exit codes - http://refspecs.linuxbase.org/LSB_2.0.1/LSB-PDA/LSB-PDA/iniscrptact.html
#   0	program is running or service is OK
#   1	program is dead and /var/run pid file exists
#   3	program is not running
#
# chkconfig: 2345 99 20
# description:  ActiveMQ runtime
# processname: activemq

NAME="activemq"
PIDFILE="/var/run/${NAME}.pid"
DAEMON="/opt/${NAME}/bin/${NAME}"
USER="activemq"

isRunning() {
  unset PID
  for each in $(ps | grep java | grep ${NAME} | awk '{print $1}'); do
    PID=${each}
  done
  if [[ "${PID}" != "" ]]; then
    echo 0
  else
    echo 1
  fi
}

case "$1" in
  start)
  	echo "Starting $NAME..."
  	su ${USER} -c "${DAEMON} console > /dev/null 2>&1 &"
    for each in $(ps | grep java | grep ${NAME} | awk '{print $1}'); do
      PID=${each}
    done
    if [[ -z ${PID} ]]; then
        echo "Failed"
        exit 1
    else
        echo ${PID} > ${PIDFILE}
        echo "Running, PID ${PID}"
    fi
  ;;
  status)
    echo "Checking ${NAME}..."
    if [[ "$(isRunning)" -ne "1" ]]; then
      echo "${NAME} is running"
      exit 0
    else
      echo "${NAME} is dead"
      rm -f ${PIDFILE}
      exit 3
    fi
  ;;
  stop)
    PID="$(isRunning)"
    if [[ "${PID}" -ne "1" ]]; then
      echo "Stopping $NAME"
      for each in $(ps | grep java | grep ${NAME} | awk '{print $1}'); do
        kill -9 ${each}
      done
      echo "Stopped"
    else
      echo "Stopped"
    fi
    if [[ -f ${PIDFILE} ]]; then
        rm -f ${PIDFILE}
        echo "${PIDFILE} removed"
    fi
    exit 3
  ;;

  restart)
    	$0 stop
    	$0 start
  ;;

  *)
          echo "Usage: $0 {status|start|stop|restart}"
          exit 1
  ;;
esac
