name    'ft-methode_activemq'
version '0.0.1'
source 'UNKNOWN'
author 'ft'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
