name    'ft-methode_activemq'
version '0.0.0'
source 'UNKNOWN'
author 'ft'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'ft/nagios', '1.5.2'
